#DATABASE CONNECTION CONFIGURATION
HOST:
PORT: "3306"
DATABASE:
USERNAME:
PASSWORD:

DROPLET_HOST:
DROPLET_PORT: "3306"
DROPLET_DATABASE:
DROPLET_USERNAME:
DROPLET_PASSWORD:

disabled_worlds:
  - example_world